### ISSUE TITLE
php artisan tahfidz:setup error when installing on Laragon

### ISSUE THREAD

**Issue by rianmadrock** [rifanmuttaqin/tahfidz-monitoring#1]
Assalamualaikum Gan, salam kenal, saya Rian, saya coba install tahfidz di Laragon error saat menjalankan perintah php artisan tahfidz:setup, saya sudah edit direktori ke mysql di Laragon saya tapi tetep error. bagaimana cara memperbaikinya? atau langkah selain command diatas adakah?

![tahfidz-error](https://user-images.githubusercontent.com/54878177/74667055-35c1d200-51d5-11ea-8d66-eca398a9c093.png)

Terima kasih.

**Comment by rifanmuttaqin** [comment]
Walikumsalam salam kenal, silahkan modifikasi semua kode pada App/Console/Commands/Database , sesuaikan dengan local server laragon. dikarenakan untuk setup artisan pada program ini masih diperuntukkan untuk pengguna Xampp

**Comment by rianmadrock** [comment]
Ok siap, terima kasih 💯
